<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="5" name="Default test" tests="25" failures="3" timestamp="25 Oct 2018 18:10:04 GMT" time="35.053" errors="0">
  <testcase name="testMethod" time="0.0" classname="TestNG.MFAC">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;Level&amp;apos; is required by @Test on method testMethod but has not been marked @Optional or defined
in C:\Users\5159473\AppData\Local\Temp\testng-eclipse--1899458647\testng-customsuite.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'Level' is required by @Test on method testMethod but has not been marked @Optional or defined
in C:\Users\5159473\AppData\Local\Temp\testng-eclipse--1899458647\testng-customsuite.xml
at org.testng.internal.Parameters.createParams(Parameters.java:290)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:359)
at org.testng.internal.Parameters.createParameters(Parameters.java:620)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testMethod -->
  <testcase name="AddressVelocity" time="11.267" classname="TestNG.MFAC"/>
  <testcase name="AddressVelocity" time="12.462" classname="TestNG.MFAC"/>
  <testcase name="AddressVelocity" time="12.829" classname="TestNG.MFAC"/>
  <testcase name="AddressVelocity" time="13.05" classname="TestNG.MFAC"/>
  <testcase name="IssuePin" time="1.53" classname="TestNG.MFAC"/>
  <testcase name="IssuePin" time="2.112" classname="TestNG.MFAC"/>
  <testcase name="IssuePin" time="2.588" classname="TestNG.MFAC"/>
  <testcase name="IssuePin" time="2.979" classname="TestNG.MFAC"/>
  <testcase name="IssuePinVelocity" time="5.594" classname="TestNG.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;5700&amp;quot; and a string containing &amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;)
     but: a string containing &amp;quot;5700&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;df544e80-d35d-471d-bac9-51b78f70b8c6&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;pinOTP&amp;quot;:&amp;quot;102453&amp;quot;,&amp;quot;pinExpirationDate&amp;quot;:&amp;quot;10/25/2018 06:39 PM GMT&amp;quot;}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"df544e80-d35d-471d-bac9-51b78f70b8c6","output":{"pinOTP":"102453","pinExpirationDate":"10/25/2018 06:39 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC.IssuePinVelocity(MFAC.java:223)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="IssuePinVelocity" time="6.741" classname="TestNG.MFAC"/>
  <testcase name="IssuePinVelocity" time="7.363" classname="TestNG.MFAC"/>
  <testcase name="IssuePinVelocity" time="7.61" classname="TestNG.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;5700&amp;quot; and a string containing &amp;quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&amp;quot;)
     but: a string containing &amp;quot;5700&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;cd06b8e4-cb37-4f41-a949-a6410b1a8ac3&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;pinOTP&amp;quot;:&amp;quot;270905&amp;quot;,&amp;quot;pinExpirationDate&amp;quot;:&amp;quot;10/25/2018 06:19 PM GMT&amp;quot;}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"cd06b8e4-cb37-4f41-a949-a6410b1a8ac3","output":{"pinOTP":"270905","pinExpirationDate":"10/25/2018 06:19 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC.IssuePinVelocity(MFAC.java:223)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="VerifyPinNoLongerValid" time="2.529" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinNoLongerValid" time="2.647" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinNoLongerValid" time="2.886" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinNoLongerValid" time="2.96" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinValid" time="1.124" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinValid" time="1.248" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinValid" time="1.324" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinValid" time="1.386" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinVelocity" time="3.172" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinVelocity" time="3.383" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinVelocity" time="4.028" classname="TestNG.MFAC"/>
  <testcase name="VerifyPinVelocity" time="4.436" classname="TestNG.MFAC"/>
  <testcase name="IssuePinExpiration" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- IssuePinExpiration -->
  <testcase name="AdditionalEnrollmentExpiration" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- AdditionalEnrollmentExpiration -->
  <testcase name="DetermineLockoutTime" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- DetermineLockoutTime -->
  <testcase name="AdditionalEnrollmentExpirationValidate" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- AdditionalEnrollmentExpirationValidate -->
  <testcase name="IssuePinExpirationValidate" time="0.0" classname="TestNG.MFAC">
    <ignored/>
  </testcase> <!-- IssuePinExpirationValidate -->
</testsuite> <!-- Default test -->
