<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="0" name="Default test" tests="25" failures="17" timestamp="30 Oct 2018 22:15:29 GMT" time="2.717" errors="0">
  <testcase name="CreateProject" time="1.605" classname="TestNG.CMAC"/>
  <testcase name="CreateProject" time="1.605" classname="TestNG.CMAC"/>
  <testcase name="CreateProject" time="1.621" classname="TestNG.CMAC"/>
  <testcase name="CreateProject" time="1.652" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.026" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;orgUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;ef1d4ae6-19c2-4ce4-bc31-44c4beee2659&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715262&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation2 103018T171526&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"ef1d4ae6-19c2-4ce4-bc31-44c4beee2659","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715262","projectName":"Proj_Creation2 103018T171526"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
  <testcase name="RetrieveProjectDetails" time="0.045" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;orgUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;09e3d145-52a0-448b-a84e-4e7903c3b585&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715261&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation1 103018T171526&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"09e3d145-52a0-448b-a84e-4e7903c3b585","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715261","projectName":"Proj_Creation1 103018T171526"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
  <testcase name="RetrieveProjectDetails" time="0.061" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;orgUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;7a1dd940-326e-4593-bed8-74d2813ea580&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715264&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation4 103018T171526&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"7a1dd940-326e-4593-bed8-74d2813ea580","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715264","projectName":"Proj_Creation4 103018T171526"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
  <testcase name="RetrieveProjectDetails" time="0.088" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;orgUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;ad480cca-8603-41c9-90a4-2c97d86d6ece&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715263&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation3 103018T171526&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "orgUUID"
     but: was "{"transactionId":"ad480cca-8603-41c9-90a4-2c97d86d6ece","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715263","projectName":"Proj_Creation3 103018T171526"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectDetails(CMAC.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectDetails -->
  <testcase name="RetrieveProjectSummary" time="0.038" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;latype&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;eaa4c85a-2430-4b12-8821-4363b4e186e3&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715261&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation1 103018T171526&amp;quot;},{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715262&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation2 103018T171526&amp;quot;},{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715263&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation3 103018T171526&amp;quot;},{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715264&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_Creation4 103018T171526&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "latype"
     but: was "{"transactionId":"eaa4c85a-2430-4b12-8821-4363b4e186e3","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715261","projectName":"Proj_Creation1 103018T171526"},{"organizationUUID":"10002","applicationUUID":"1030181715262","projectName":"Proj_Creation2 103018T171526"},{"organizationUUID":"10002","applicationUUID":"1030181715263","projectName":"Proj_Creation3 103018T171526"},{"organizationUUID":"10002","applicationUUID":"1030181715264","projectName":"Proj_Creation4 103018T171526"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveProjectSummary(CMAC.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveProjectSummary -->
  <testcase name="RetrieveResource" time="0.016" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;endpointUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;e69f94cc-7129-4f21-b4dc-fc422c28069f&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;resources&amp;quot;:[]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"e69f94cc-7129-4f21-b4dc-fc422c28069f","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveResource(CMAC.java:240)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="RetrieveResource" time="0.015" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;endpointUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;65d36984-122d-4d28-910b-391a1c5e1a15&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;resources&amp;quot;:[]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"65d36984-122d-4d28-910b-391a1c5e1a15","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveResource(CMAC.java:240)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="RetrieveResource" time="0.047" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;endpointUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;85f59e16-d9fc-432d-9b33-04938ea64834&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;resources&amp;quot;:[]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"85f59e16-d9fc-432d-9b33-04938ea64834","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveResource(CMAC.java:240)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="RetrieveResource" time="0.059" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;endpointUUID&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;f3d158fa-06c3-4b9c-9898-381f2be74869&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;resources&amp;quot;:[]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "endpointUUID"
     but: was "{"transactionId":"f3d158fa-06c3-4b9c-9898-381f2be74869","output":{"resources":[]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.RetrieveResource(CMAC.java:240)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- RetrieveResource -->
  <testcase name="CreateResource" time="0.015" classname="TestNG.CMAC"/>
  <testcase name="CreateResource" time="0.031" classname="TestNG.CMAC"/>
  <testcase name="CreateResource" time="0.047" classname="TestNG.CMAC"/>
  <testcase name="CreateResource" time="0.078" classname="TestNG.CMAC"/>
  <testcase name="UpdateProject" time="0.042" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;\&amp;quot;latype\&amp;quot;:\&amp;quot;propreitary&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;39363e0c-810e-4578-bed1-2fb54b3aa8db&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715262&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_DEL_Updated103018T171528&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "\"latype\":\"propreitary"
     but: was "{"transactionId":"39363e0c-810e-4578-bed1-2fb54b3aa8db","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715262","projectName":"Proj_DEL_Updated103018T171528"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.UpdateProject(CMAC.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateProject -->
  <testcase name="UpdateProject" time="0.089" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;\&amp;quot;latype\&amp;quot;:\&amp;quot;propreitary&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;7fca0885-c365-4699-8d63-35ac33978b70&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715261&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_DEL_Updated103018T171528&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "\"latype\":\"propreitary"
     but: was "{"transactionId":"7fca0885-c365-4699-8d63-35ac33978b70","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715261","projectName":"Proj_DEL_Updated103018T171528"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.UpdateProject(CMAC.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateProject -->
  <testcase name="UpdateProject" time="0.104" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;\&amp;quot;latype\&amp;quot;:\&amp;quot;propreitary&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;86ecdc6d-25b3-41e6-a6d3-bea4cb615698&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715263&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_DEL_Updated103018T171528&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "\"latype\":\"propreitary"
     but: was "{"transactionId":"86ecdc6d-25b3-41e6-a6d3-bea4cb615698","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715263","projectName":"Proj_DEL_Updated103018T171528"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.UpdateProject(CMAC.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateProject -->
  <testcase name="UpdateProject" time="0.136" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;\&amp;quot;latype\&amp;quot;:\&amp;quot;propreitary&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;a8efb59e-b8db-4a28-b3f6-0bd272d0e3c3&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;projects&amp;quot;:[{&amp;quot;organizationUUID&amp;quot;:&amp;quot;10002&amp;quot;,&amp;quot;applicationUUID&amp;quot;:&amp;quot;1030181715264&amp;quot;,&amp;quot;projectName&amp;quot;:&amp;quot;Proj_DEL_Updated103018T171528&amp;quot;}]}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "\"latype\":\"propreitary"
     but: was "{"transactionId":"a8efb59e-b8db-4a28-b3f6-0bd272d0e3c3","output":{"projects":[{"organizationUUID":"10002","applicationUUID":"1030181715264","projectName":"Proj_DEL_Updated103018T171528"}]}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.UpdateProject(CMAC.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- UpdateProject -->
  <testcase name="DeleteProject" time="0.047" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;PROJNOTEXIST&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;dc454a13-33a9-4950-893c-6f5fe97feb18&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;PROJECT_NOT_EXIST&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unable to delete. Project with applicationUUID doesn&amp;apos;t exist.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "PROJNOTEXIST"
     but: was "{"transactionId":"dc454a13-33a9-4950-893c-6f5fe97feb18","errors":[{"code":"PROJECT_NOT_EXIST","message":"Unable to delete. Project with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.DeleteProject(CMAC.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteProject -->
  <testcase name="DeleteProject" time="0.109" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;PROJNOTEXIST&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;320c726a-c98e-4d4b-8e1d-c47f31f10131&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;PROJECT_NOT_EXIST&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unable to delete. Project with applicationUUID doesn&amp;apos;t exist.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "PROJNOTEXIST"
     but: was "{"transactionId":"320c726a-c98e-4d4b-8e1d-c47f31f10131","errors":[{"code":"PROJECT_NOT_EXIST","message":"Unable to delete. Project with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.DeleteProject(CMAC.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteProject -->
  <testcase name="DeleteProject" time="0.125" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;PROJNOTEXIST&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;429d9881-3f1c-4034-a7e2-d9cddf583af1&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;PROJECT_NOT_EXIST&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unable to delete. Project with applicationUUID doesn&amp;apos;t exist.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "PROJNOTEXIST"
     but: was "{"transactionId":"429d9881-3f1c-4034-a7e2-d9cddf583af1","errors":[{"code":"PROJECT_NOT_EXIST","message":"Unable to delete. Project with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.DeleteProject(CMAC.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteProject -->
  <testcase name="DeleteProject" time="0.155" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;PROJNOTEXIST&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;d09363a7-4b76-4d13-b3de-464398f8ccbc&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;PROJECT_NOT_EXIST&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Unable to delete. Project with applicationUUID doesn&amp;apos;t exist.&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "PROJNOTEXIST"
     but: was "{"transactionId":"d09363a7-4b76-4d13-b3de-464398f8ccbc","errors":[{"code":"PROJECT_NOT_EXIST","message":"Unable to delete. Project with applicationUUID doesn't exist."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.DeleteProject(CMAC.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- DeleteProject -->
</testsuite> <!-- Default test -->
